# Site settings
title: Laboratório de Sistemas Autônomos 
email: 
url: https://github.com/robotics-pucrs
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
#skills: <span>UAVs &bull; Barcos &bull; Veículos Trrestres &bull; Mini UAVs &bull; Humanoides &bull; Gerais</span>
skills: Escola Politécnica &bull; PUCRS
meta_author: LSA

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 052439 # 0477F
  primary-rgb: "128,100,255" # cor do fundo passar o mouse pelo icone
  secondary:  00477F # 052439 
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Copyright &copy; 2024-2025 Laboratório de Sistemas Autônomos da PUCRS
  location: Endereço
  social: github
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/robotics-pucrs

# Postal address (add as many lines as necessary)
address:
  - line: Laboratório de Sistemas Autônomos
  - line: Escola Politecnica da PUCRS
  - line: Av. Ipiranga, 6681 Sala 32/725
  - line: Porto Alegre - Brasil - 90619-900
  - line: Fone +55 (51) 3353-8700

# Credits content
credits: 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
